### PR TITLE
Bumped qlobber@4.2.0

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes/issues/373

**Comment by mcollina** [comment]
I did land this, however I'm definitely not happy that it ships a binary addon that needs to be compiled every time it is installed for a feature that I do not need.

**Comment by mcollina** [comment]
Unfortunately, I would recommend to not update to qlobberr@4 https://github.com/davedoesdev/qlobber/issues/17

**Comment by robertsLando** [comment]
@mcollina How should we handle this so? This update is needed to fix this bug on aedes: https://github.com/moscajs/aedes/issues/373

**Pull request merged**
